// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXPH0ZUydU3aXwmbrzUmThRnuZ6AAhgo',
    appId: '1:162036994872:web:956753f6c5b13b414da7cd',
    messagingSenderId: '162036994872',
    projectId: 'newsnow-39df1',
    authDomain: 'newsnow-39df1.firebaseapp.com',
    storageBucket: 'newsnow-39df1.appspot.com',
    measurementId: 'G-T94HJLS6DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm6TsIE6kqXt0lJASChgv4Sm0LSh9OuM0',
    appId: '1:162036994872:android:39c95d64db24bf314da7cd',
    messagingSenderId: '162036994872',
    projectId: 'newsnow-39df1',
    storageBucket: 'newsnow-39df1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NrXNoeZshBJT3FPzM8_Twm12vYWGdns',
    appId: '1:162036994872:ios:2e94d1725f19dbdb4da7cd',
    messagingSenderId: '162036994872',
    projectId: 'newsnow-39df1',
    storageBucket: 'newsnow-39df1.appspot.com',
    iosBundleId: 'com.example.newsNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0NrXNoeZshBJT3FPzM8_Twm12vYWGdns',
    appId: '1:162036994872:ios:2e94d1725f19dbdb4da7cd',
    messagingSenderId: '162036994872',
    projectId: 'newsnow-39df1',
    storageBucket: 'newsnow-39df1.appspot.com',
    iosBundleId: 'com.example.newsNow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXPH0ZUydU3aXwmbrzUmThRnuZ6AAhgo',
    appId: '1:162036994872:web:9411d5c42299f8d54da7cd',
    messagingSenderId: '162036994872',
    projectId: 'newsnow-39df1',
    authDomain: 'newsnow-39df1.firebaseapp.com',
    storageBucket: 'newsnow-39df1.appspot.com',
    measurementId: 'G-0GYRWRELM8',
  );
}
